### ISSUE TITLE
最新的版本还应当使用2.8版本的schedhorizon吗

### ISSUE THREAD

**Issue by paipoex** [TEACAET/android_kernel_samsung_sm8450_5.10.198#1]
感觉卡顿情况变多了。作者有使用什么调度吗？同样，3.0版本的TEACAET-KERNEL-GPU还有效吗，之前刷驱动还是黑屏了，或者说对于刷入顺序有要求？

**Comment by TEACAET** [comment]
调度我一直用的schedhorizon的powersave模式。TEACAET-KERNEL-GPU经过验证并没有解决掉驱动的问题，所以几乎没什么用的。gpu驱动可能需要刷入附加模块后重启，再单独刷入gpu驱动才能生效，之后刷其他模块后重启前再重刷一遍gpu驱动才能不掉驱动（我也不知道为什么有这问题)
我一会更新一下我现在用的版本，其他方面我现在用的15.5.03.1的桌面（continuity service不可冻结，冻结会导致桌面闪退）和505mhz-820mhz的gpu降压，gpu驱动用的是v783。另外用V4.5的话可能更需要使用墓碑软件，我使用的是最新版的noacvtive

**Comment by paipoex** [comment]
感谢，现在基本按照给出的方案调整了一下，给的驱动没有掉了，也没有大问题，只是多任务界面有时会鬼畜。

**Comment by paipoex** [comment]
你用这桌面会有文件夹打开时闪一下的问题吗，我遇到了，但没看到有相同问题的，看看是个例还是机型的问题

**Comment by TEACAET** [comment]
这个版本的问题，5.05新版本会有壁纸缩放丢失问题。目前解决办法是只要文件夹不止一页就不会闪&nbsp;


TEACAET
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月13日(星期五) 晚上7:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TEACAET/android_kernel_samsung_sm8450_5.10.198] 最新的版本还应当使用2.8版本的schedhorizon吗 (Issue #1)














 
你用这桌面会有文件夹打开时闪一下的问题吗，我遇到了，但没看到有相同问题的，看看是个例还是机型的问题

**Comment by paipoex** [comment]
了解了，感谢
